/*
 * 调度器管理后端
 * ## 错误规则  ###    401 - 未登录，如果出现这个错误，请调用 登录/自动登录 接口刷新session或者requresttoken ###    403 - 权限不足， 一般不会出现这个错误 ###    417 - 碰到这个错误请将response的body解析为ErrorInfo一般情况是直接将ErrorInfo中的errorMessage 直接展现给用户 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package me.laiyijie.job.android.io.swagger.api;

import me.laiyijie.job.android.io.swagger.ApiException;
import me.laiyijie.job.android.io.swagger.model.ExecutorGroup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExecutorGroupApi
 */
@Ignore
public class ExecutorGroupApiTest {

    private final ExecutorGroupApi api = new ExecutorGroupApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executorGroupsGetTest() throws ApiException {
        List<ExecutorGroup> response = api.executorGroupsGet();

        // TODO: test validations
    }
    
    /**
     * 删除整个group，但是还在运行的执行机还是会重新生成这个group，会清空当前group下的所有执行机记录
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executorGroupsGroupNameDeleteTest() throws ApiException {
        String groupName = null;
        api.executorGroupsGroupNameDelete(groupName);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executorGroupsGroupNameGetTest() throws ApiException {
        String groupName = null;
        ExecutorGroup response = api.executorGroupsGroupNameGet(groupName);

        // TODO: test validations
    }
    
    /**
     * 只能修改描述
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executorGroupsGroupNamePutTest() throws ApiException {
        String groupName = null;
        ExecutorGroup executorGroup = null;
        api.executorGroupsGroupNamePut(groupName, executorGroup);

        // TODO: test validations
    }
    
    /**
     * 添加执行机组
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executorGroupsPostTest() throws ApiException {
        ExecutorGroup executorGroup = null;
        String response = api.executorGroupsPost(executorGroup);

        // TODO: test validations
    }
    
}
