swagger: '2.0'

info:
  version: "0.0.1"
  title: 调度器管理后端
  description: |
    ## 错误规则

    ###    401 - 未登录，如果出现这个错误，请调用 登录/自动登录 接口刷新session或者requresttoken
    ###    403 - 权限不足， 一般不会出现这个错误
    ###    417 - 碰到这个错误请将response的body解析为ErrorInfo一般情况是直接将ErrorInfo中的errorMessage 直接展现给用户
    
host: 58.87.75.73:8888
basePath: /job/api/v1/

produces:
  - application/json
  - text/plain; charset=utf-8
consumes:
  - application/x-www-form-urlencoded
  - application/json
  - multipart/form-data
  - text/plain; charset=utf-8
  - "*/*"
schemes:
  - http
tags:
    - name: Test
      description: 测试接口
    - name: ExecutorGroup
      description: 执行组
    - name: Job

paths:
  /test/info:
    get:
      tags:
        - Test
      summary: 测试接口
      parameters:
        - name: word
          in: query
          description: 你想说的话
          required: true
          type: string
      responses:
        200:
          description: 回复你的信息
          schema:
            title: TestResponse
            type: object
            properties:
              myWord:
                type: string
                description: 返回你说的话
              count:
                type: integer
                format: int64
                description: 返回一个计数          
           
  /auth/login:
    post:
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - Auth
      parameters:
        - name: username
          in: formData
          type: string
          required: true
        - name: password
          in: formData
          type: string
          required: true
      responses:
        200: 
          description: ok
  
 
  /rules:
    get:
      tags:
        - Rules
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/Rule'
   
    post:
      tags:
        - Rules
      summary: 添加规则
      parameters:
        - name: rule
          in: body
          required: true
          schema:
            $ref: '#/definitions/Rule'
      responses:
        200:
          description: ok
  
  /rules/{ruleId}:
    put:
      tags:
        - Rules
      summary: 修改规则
      parameters:
        - name: ruleId
          in: path
          required: true
          type: integer
        - name: rule
          in: body
          required: true
          schema:
            $ref: '#/definitions/Rule'
      responses:
        200:
          description: ok
          
          
    delete:
      summary: 删除规则
      tags:
        - Rules
      parameters:
        - name: ruleId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: ok
  
  /executor/groups:
    get:
      tags:
        - ExecutorGroup
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/ExecutorGroup'
   
    post:
      tags:
        - ExecutorGroup
      summary: 添加执行机组
      parameters:
        - name: executorGroup
          in: body
          required: true
          schema:
            $ref: '#/definitions/ExecutorGroup'
      responses:
        200:
          description: ok
         
  /executor/groups/{groupName}:
    get:
      tags:
        - ExecutorGroup
      parameters:
        - name: groupName
          in: path
          required: true
          type: string
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/ExecutorGroup'
            
    put:
      tags:
        - ExecutorGroup
      summary: 只能修改描述
      parameters:
        - name: groupName
          in: path
          required: true
          type: string
        - name: executorGroup
          in: body
          required: true
          schema:
            $ref: '#/definitions/ExecutorGroup'
      responses:
        200:
          description: ok
    
    delete:
      summary: 删除整个group，但是还在运行的执行机还是会重新生成这个group，会清空当前group下的所有执行机记录
      tags:
        - ExecutorGroup
      parameters:
        - name: groupName
          in: path
          type: string
          required: true
      responses:
        200:
          description: ok

  /workflows:
    get:
      tags:
        - Job
      summary: 获取工作流列表
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/WorkFlow'
    post:
      tags:
        - Job
      summary: 创建一个工作流
      parameters:
        - name: workFlow
          in: body
          required: true
          schema:
            $ref: '#/definitions/WorkFlow'
      responses:
        200: 
          description: ok
          schema:
            type: integer
  
  /workflows/{workFlowId}:
    get:
      tags:
        - Job
      summary: 获取单个工作流信息
      parameters:
        - name: workFlowId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/WorkFlow'
    post:
      tags:
        - Job
      summary: 修改这个工作流信息，只能修改 名字、描述、执行间隔、是否循环执行
      parameters:
        - name: workFlowId
          in: path
          type: integer
          required: true
        - name: workFlow
          in: body
          required: true
          schema:
            $ref: '#/definitions/WorkFlow'
      responses:
        200: 
          description: ok
          
    delete:
      tags:
        - Job
      summary: 删除这个工作流
      parameters:
        - name: workFlowId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: ok
  
  /workflows/{workFlowId}/run:
    post:
      tags:
        - Job
      summary: 从头执行这个workflow
      parameters:
        - name: workFlowId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: ok
  /workflows/{workFlowId}/stop:
    post:
      tags:
        - Job
      summary: 停止这个workflow
      parameters:
        - name: workFlowId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: ok
  /workflows/{workFlowId}/resume:
    post:
      tags:
        - Job
      summary: 从失败处执行这个workflow
      parameters:
        - name: workFlowId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: ok  
  
  /workflows/{workFlowId}/job/groups:
    get:
      tags:
        - Job
      summary: 获取工作流下的所有执行组
      parameters:
        - name: workFlowId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/JobGroup'
              
  /job/groups:
    post:
      tags:
        - Job
      summary: 创建一个jobgroup 名字、第几步、描述
      parameters:
        - name: jobGroup
          in: body
          required: true
          schema:
            $ref: '#/definitions/JobGroup'
      responses:
        200:
          description: ok
  
  /job/groups/{groupId}:
    get:
      tags:
        - Job
      summary: 获取单个执行组的信息
      parameters:
        - name: groupId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/JobGroup'
    post:
      tags:
        - Job
      summary: 修改jobgroup信息 只能修改 名字、第几步、描述
      parameters:
        - name: groupId
          in: path
          type: integer
          required: true
        - name: jobGroup
          in: body
          required: true
          schema:
            $ref: '#/definitions/JobGroup'
      responses:
        200:
          description: ok
    delete:
      tags:
        - Job
      summary: 删除jobgroup
      parameters:
        - name: groupId
          in: path
          type: integer
          required: true      
      responses:
        200:
          description: ok
  /job/groups/{groupId}/jobs:
    get:
      tags:
        - Job
      parameters:
        - name: groupId
          type: integer
          required: true
          in: path
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/Job'
            
  /jobs:
    post:
      tags:
        - Job
      parameters:
        - name: job
          in: body
          required: true
          schema:
            $ref: '#/definitions/Job'
            
      responses:
        200:
          description: ok
          
  /jobs/{jobId}:
    get:
      tags:
        - Job
      parameters:
        - name: jobId
          type: integer
          required: true
          in: path
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/Job'
    post:
      tags:
        - Job
      summary: 修改job 信息 只能修改 名字、描述、脚本、使用的执行机组
      parameters:
        - name: jobId
          type: integer
          required: true
          in: path
        - name: job
          required: true
          in: body
          schema:
            $ref: '#/definitions/Job'
      responses:
        200:
          description: ok
    
    delete:
      tags:
        - Job
      parameters:
        - name: jobId
          type: integer
          required: true
          in: path
      responses:
        200:
          description: ok
  /jobs/{jobId}/run:
    post:
      tags:
        - Job
      parameters:
        - name: jobId
          type: integer
          required: true
          in: path
      responses:
        200:
          description: ok
  /jobs/{jobId}/stop:
    post:
      tags:
        - Job
      parameters:
        - name: jobId
          type: integer
          required: true
          in: path
      responses:
        200:
          description: ok
  /jobs/{jobId}/error/log:
    get:
      tags:
        - Job
      summary: 根据jobid来查错误日志
      parameters:
        - name: jobId
          type: integer
          required: true
          in: path
        - name: pageSize
          type: integer
          required: true
          in: query
        - name: pageNum
          type: integer
          required: true
          in: query
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/JobErrorLog'
              
  /job/error/logs:
    get:
      tags:
        - Job
      summary: 所有的错误日志
      parameters:
        - name: pageSize
          type: integer
          required: true
          in: query
        - name: pageNum
          type: integer
          required: true
          in: query
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/JobErrorLog'      
  
definitions:
  Rule:
    type: object
    properties:
      id:
        type: integer
        description: id
      script:
        type: string
        description: 脚本名称
      pattern:
        type: string
        description: 匹配的字符串
      retryTimes:
        type: number
        description: 重试次数

  Executor:
    type: object
    properties:
      name:
        type: string
        description: 唯一的名字，不能重复，代表不同的执行机
      ipAddress:
        type: string
      onlineStatus:
        type: string
        
  ExecutorGroup:
    type: object
    properties:
      name:
        type: string
        description: 唯一的名字，不能重复，代表唯一的执行组
      description:
        type: string
      executors:
        type: array
        items: 
          $ref: '#/definitions/Executor'
          
  WorkFlow:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string
      runInterval:
        type: integer
      status:
        type: string
      isCircleScheduled:
        type: boolean
        description: 是否打开循环调度
      
  
  JobGroup:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string
      status:
        type: string
      step:
        type: integer 
        description: 根据这个数字来进行按顺序执行
      workFlowId:
        type: integer
  
  Job:
    type: object
    properties:
      id:
        type: integer
      name: 
        type: string
      description:
        type: string
      status:
        type: string
      jobGroupId:
        type: integer
      retryRegex:
        type: string
      maxRetryTimes:
        type: integer
      currentRetryTimes:
        type: integer
      executorGroup:
        $ref: "#/definitions/ExecutorGroup"
      currentExecutor:
        $ref: '#/definitions/Executor'
      script:
        type: string
  
  JobErrorLog:
    type: object
    properties:
      id:
        type: integer
        format: int64
      workflowId:
        type: integer
      jobGroupId:
        type: integer
      jobId:
        type: integer
      time:
        type: integer
        format: int64
      executorName:
        type: string
      content:
        type: string


  ErrorInfo:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string

