#import <Foundation/Foundation.h>
#import "LJobRule.h"
#import "LJobApi.h"

/**
* 调度器管理后端
* ## 错误规则  ###    401 - 未登录，如果出现这个错误，请调用 登录/自动登录 接口刷新session或者requresttoken ###    403 - 权限不足， 一般不会出现这个错误 ###    417 - 碰到这个错误请将response的body解析为ErrorInfo一般情况是直接将ErrorInfo中的errorMessage 直接展现给用户 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface LJobRulesApi: NSObject <LJobApi>

extern NSString* kLJobRulesApiErrorDomain;
extern NSInteger kLJobRulesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(LJobApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// 
///  code:200 message:"ok"
///
/// @return NSArray<LJobRule>*
-(NSURLSessionTask*) rulesGetWithCompletionHandler: 
    (void (^)(NSArray<LJobRule>* output, NSError* error)) handler;


/// 添加规则
/// 
///
/// @param rule 
/// 
///  code:200 message:"ok"
///
/// @return 
-(NSURLSessionTask*) rulesPostWithRule: (LJobRule*) rule
    completionHandler: (void (^)(NSError* error)) handler;


/// 删除规则
/// 
///
/// @param ruleId 
/// 
///  code:200 message:"ok"
///
/// @return 
-(NSURLSessionTask*) rulesRuleIdDeleteWithRuleId: (NSNumber*) ruleId
    completionHandler: (void (^)(NSError* error)) handler;


/// 修改规则
/// 
///
/// @param ruleId 
/// @param rule 
/// 
///  code:200 message:"ok"
///
/// @return 
-(NSURLSessionTask*) rulesRuleIdPutWithRuleId: (NSNumber*) ruleId
    rule: (LJobRule*) rule
    completionHandler: (void (^)(NSError* error)) handler;



@end
