#import <Foundation/Foundation.h>
#import "LJobExecutorGroup.h"
#import "LJobApi.h"

/**
* 调度器管理后端
* ## 错误规则  ###    401 - 未登录，如果出现这个错误，请调用 登录/自动登录 接口刷新session或者requresttoken ###    403 - 权限不足， 一般不会出现这个错误 ###    417 - 碰到这个错误请将response的body解析为ErrorInfo一般情况是直接将ErrorInfo中的errorMessage 直接展现给用户 
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface LJobDefaultApi: NSObject <LJobApi>

extern NSString* kLJobDefaultApiErrorDomain;
extern NSInteger kLJobDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(LJobApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param groupId 
/// @param executorId executorId
/// 
///  code:200 message:"ok"
///
/// @return 
-(NSURLSessionTask*) executorgroupGroupIdExecutorDeleteWithGroupId: (NSNumber*) groupId
    executorId: (NSNumber*) executorId
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 
///
/// @param groupId 
/// @param executorId executorId
/// 
///  code:200 message:"ok"
///
/// @return 
-(NSURLSessionTask*) executorgroupGroupIdExecutorPostWithGroupId: (NSNumber*) groupId
    executorId: (NSNumber*) executorId
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 
///
/// @param groupId 
/// 
///  code:200 message:"ok"
///
/// @return LJobExecutorGroup*
-(NSURLSessionTask*) executorgroupGroupIdGetWithGroupId: (NSNumber*) groupId
    completionHandler: (void (^)(LJobExecutorGroup* output, NSError* error)) handler;


/// 
/// 
///
/// @param groupId 
/// @param name  (optional)
/// @param _description  (optional)
/// 
///  code:200 message:"ok"
///
/// @return 
-(NSURLSessionTask*) executorgroupGroupIdPutWithGroupId: (NSNumber*) groupId
    name: (NSString*) name
    _description: (NSString*) _description
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"ok"
///
/// @return NSArray<LJobExecutorGroup>*
-(NSURLSessionTask*) executorgroupsGetWithCompletionHandler: 
    (void (^)(NSArray<LJobExecutorGroup>* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"ok"
///
/// @return NSNumber*
-(NSURLSessionTask*) executorgroupsPostWithCompletionHandler: 
    (void (^)(NSNumber* output, NSError* error)) handler;



@end
