/*
 * 调度器管理后端
 * ## 错误规则  ###    401 - 未登录，如果出现这个错误，请调用 登录/自动登录 接口刷新session或者requresttoken ###    403 - 权限不足， 一般不会出现这个错误 ###    417 - 碰到这个错误请将response的body解析为ErrorInfo一般情况是直接将ErrorInfo中的errorMessage 直接展现给用户 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package me.laiyijie.job.android.io.swagger.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import me.laiyijie.job.android.io.swagger.model.Executor;
import me.laiyijie.job.android.io.swagger.model.ExecutorGroup;
import java.io.Serializable;

/**
 * Job
 */

public class Job implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("jobGroupName")
  private String jobGroupName = null;

  @SerializedName("executorGroup")
  private ExecutorGroup executorGroup = null;

  @SerializedName("currentExecutor")
  private Executor currentExecutor = null;

  @SerializedName("script")
  private String script = null;

  public Job id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Job name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Job description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Job status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Job jobGroupName(String jobGroupName) {
    this.jobGroupName = jobGroupName;
    return this;
  }

   /**
   * Get jobGroupName
   * @return jobGroupName
  **/
  @ApiModelProperty(value = "")
  public String getJobGroupName() {
    return jobGroupName;
  }

  public void setJobGroupName(String jobGroupName) {
    this.jobGroupName = jobGroupName;
  }

  public Job executorGroup(ExecutorGroup executorGroup) {
    this.executorGroup = executorGroup;
    return this;
  }

   /**
   * Get executorGroup
   * @return executorGroup
  **/
  @ApiModelProperty(value = "")
  public ExecutorGroup getExecutorGroup() {
    return executorGroup;
  }

  public void setExecutorGroup(ExecutorGroup executorGroup) {
    this.executorGroup = executorGroup;
  }

  public Job currentExecutor(Executor currentExecutor) {
    this.currentExecutor = currentExecutor;
    return this;
  }

   /**
   * Get currentExecutor
   * @return currentExecutor
  **/
  @ApiModelProperty(value = "")
  public Executor getCurrentExecutor() {
    return currentExecutor;
  }

  public void setCurrentExecutor(Executor currentExecutor) {
    this.currentExecutor = currentExecutor;
  }

  public Job script(String script) {
    this.script = script;
    return this;
  }

   /**
   * Get script
   * @return script
  **/
  @ApiModelProperty(value = "")
  public String getScript() {
    return script;
  }

  public void setScript(String script) {
    this.script = script;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Job job = (Job) o;
    return Objects.equals(this.id, job.id) &&
        Objects.equals(this.name, job.name) &&
        Objects.equals(this.description, job.description) &&
        Objects.equals(this.status, job.status) &&
        Objects.equals(this.jobGroupName, job.jobGroupName) &&
        Objects.equals(this.executorGroup, job.executorGroup) &&
        Objects.equals(this.currentExecutor, job.currentExecutor) &&
        Objects.equals(this.script, job.script);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, status, jobGroupName, executorGroup, currentExecutor, script);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Job {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    jobGroupName: ").append(toIndentedString(jobGroupName)).append("\n");
    sb.append("    executorGroup: ").append(toIndentedString(executorGroup)).append("\n");
    sb.append("    currentExecutor: ").append(toIndentedString(currentExecutor)).append("\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

