/*
 * 调度器管理后端
 * ## 错误规则  ###    401 - 未登录，如果出现这个错误，请调用 登录/自动登录 接口刷新session或者requresttoken ###    403 - 权限不足， 一般不会出现这个错误 ###    417 - 碰到这个错误请将response的body解析为ErrorInfo一般情况是直接将ErrorInfo中的errorMessage 直接展现给用户 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package me.laiyijie.job.android.io.swagger.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * JobErrorLog
 */

public class JobErrorLog implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("workflowId")
  private Integer workflowId = null;

  @SerializedName("jobGroupId")
  private Integer jobGroupId = null;

  @SerializedName("jobId")
  private Integer jobId = null;

  @SerializedName("time")
  private Long time = null;

  @SerializedName("executorName")
  private String executorName = null;

  @SerializedName("content")
  private String content = null;

  public JobErrorLog id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public JobErrorLog workflowId(Integer workflowId) {
    this.workflowId = workflowId;
    return this;
  }

   /**
   * Get workflowId
   * @return workflowId
  **/
  @ApiModelProperty(value = "")
  public Integer getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(Integer workflowId) {
    this.workflowId = workflowId;
  }

  public JobErrorLog jobGroupId(Integer jobGroupId) {
    this.jobGroupId = jobGroupId;
    return this;
  }

   /**
   * Get jobGroupId
   * @return jobGroupId
  **/
  @ApiModelProperty(value = "")
  public Integer getJobGroupId() {
    return jobGroupId;
  }

  public void setJobGroupId(Integer jobGroupId) {
    this.jobGroupId = jobGroupId;
  }

  public JobErrorLog jobId(Integer jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  @ApiModelProperty(value = "")
  public Integer getJobId() {
    return jobId;
  }

  public void setJobId(Integer jobId) {
    this.jobId = jobId;
  }

  public JobErrorLog time(Long time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @ApiModelProperty(value = "")
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public JobErrorLog executorName(String executorName) {
    this.executorName = executorName;
    return this;
  }

   /**
   * Get executorName
   * @return executorName
  **/
  @ApiModelProperty(value = "")
  public String getExecutorName() {
    return executorName;
  }

  public void setExecutorName(String executorName) {
    this.executorName = executorName;
  }

  public JobErrorLog content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobErrorLog jobErrorLog = (JobErrorLog) o;
    return Objects.equals(this.id, jobErrorLog.id) &&
        Objects.equals(this.workflowId, jobErrorLog.workflowId) &&
        Objects.equals(this.jobGroupId, jobErrorLog.jobGroupId) &&
        Objects.equals(this.jobId, jobErrorLog.jobId) &&
        Objects.equals(this.time, jobErrorLog.time) &&
        Objects.equals(this.executorName, jobErrorLog.executorName) &&
        Objects.equals(this.content, jobErrorLog.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, workflowId, jobGroupId, jobId, time, executorName, content);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobErrorLog {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    jobGroupId: ").append(toIndentedString(jobGroupId)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    executorName: ").append(toIndentedString(executorName)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

